---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-vault-fedora
    image: ghcr.io/avnes/molecule-fedora:36
    pre_build_image: true
  - name: ansible-role-vault-ubuntu
    image: ghcr.io/avnes/molecule-ubuntu:latest
    pre_build_image: true
  - name: ansible-role-vault-centos
    image: ghcr.io/avnes/molecule-centos-stream:8.0.1
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: False
  options:
    vvv: True
lint: |
  yamllint .
  ansible-lint
verifier:
  name: ansible
